version: '3'
services:

  #PHP Service
  app:
    container_name: rsonbhouse-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./deployment/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      VIRTUAL_HOST: rson.arnoldjoslive.com
    networks:
      - rsonapp-network

  #Nginx Service
  # webserver:
  #   container_name: rsonbhouse-webserver
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./:/var/www
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./deployment/nginx/:/etc/nginx/conf.d/
  #   networks:
  #     - rsonapp-network
    # image: nginx:alpine
    # restart: unless-stopped
    # tty: true
    # ports:
    #   - "8000:80"
    #   - "8500:443"
    # volumes:
    #   - ./:/var/www
    #   - ./deployment/nginx/:/etc/nginx/conf.d/
    #

  #MySQL Service
  db:
    container_name: rsonbhouse-db
    image: mysql
    restart: always
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: gboardinghouse
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
      - ./deployment/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - rsonapp-network
    command: --default-authentication-plugin=mysql_native_password

#Docker Networks
# networks:
# 	default:
# 		external:
# 			name:

networks:
  rsonapp-network:

#Docker Volumes
volumes:
  dbdata: