version: '3'
services:

  #PHP Service
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./deployment/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    container_name: webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./deployment/nginx/:/etc/nginx/conf.d/
    environment:
      VIRTUAL_HOST: rson.arnoldjoslive.com

  #MySQL Service
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: gboardinghouse
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
      - ./deployment/mysql/my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password

#Docker Networks
networks:
  default:
    external:
      name: nginx-proxy

#Docker Volumes
volumes:
  dbdata: